//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect1
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Imagine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imagine()
        {
            this.DetaliiComandas = new HashSet<DetaliiComanda>();
        }

        [DataMember]public int ImagineId { get; set; }
        [DataMember]public string Titlu { get; set; }
        [DataMember]public string Descriere { get; set; }
        [DataMember]public System.DateTime DataImagine { get; set; }
        [DataMember]public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]public virtual ICollection<DetaliiComanda> DetaliiComandas { get; set; }
    }
}
