//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect3WPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Comanda[] ComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Comanda[] Comandas {
            get {
                return this.ComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandasField, value) != true)) {
                    this.ComandasField = value;
                    this.RaisePropertyChanged("Comandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet {
            get {
                return this.JudetField;
            }
            set {
                if ((object.ReferenceEquals(this.JudetField, value) != true)) {
                    this.JudetField = value;
                    this.RaisePropertyChanged("Judet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate {
            get {
                return this.LocalitateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitateField, value) != true)) {
                    this.LocalitateField = value;
                    this.RaisePropertyChanged("Localitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Automobil AutomobilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFinalizareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataProgramareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KmBordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StareComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValoarePieseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Automobil Automobil {
            get {
                return this.AutomobilField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomobilField, value) != true)) {
                    this.AutomobilField = value;
                    this.RaisePropertyChanged("Automobil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId {
            get {
                return this.ComandaIdField;
            }
            set {
                if ((this.ComandaIdField.Equals(value) != true)) {
                    this.ComandaIdField = value;
                    this.RaisePropertyChanged("ComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizare {
            get {
                return this.DataFinalizareField;
            }
            set {
                if ((this.DataFinalizareField.Equals(value) != true)) {
                    this.DataFinalizareField = value;
                    this.RaisePropertyChanged("DataFinalizare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataProgramare {
            get {
                return this.DataProgramareField;
            }
            set {
                if ((this.DataProgramareField.Equals(value) != true)) {
                    this.DataProgramareField = value;
                    this.RaisePropertyChanged("DataProgramare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem {
            get {
                return this.DataSystemField;
            }
            set {
                if ((this.DataSystemField.Equals(value) != true)) {
                    this.DataSystemField = value;
                    this.RaisePropertyChanged("DataSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandas {
            get {
                return this.DetaliiComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliiComandasField, value) != true)) {
                    this.DetaliiComandasField = value;
                    this.RaisePropertyChanged("DetaliiComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord {
            get {
                return this.KmBordField;
            }
            set {
                if ((this.KmBordField.Equals(value) != true)) {
                    this.KmBordField = value;
                    this.RaisePropertyChanged("KmBord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StareComanda {
            get {
                return this.StareComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.StareComandaField, value) != true)) {
                    this.StareComandaField = value;
                    this.RaisePropertyChanged("StareComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese {
            get {
                return this.ValoarePieseField;
            }
            set {
                if ((this.ValoarePieseField.Equals(value) != true)) {
                    this.ValoarePieseField = value;
                    this.RaisePropertyChanged("ValoarePiese");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Automobil", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Automobil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Comanda[] ComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumarAutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Sasiu SasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieSasiuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Comanda[] Comandas {
            get {
                return this.ComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandasField, value) != true)) {
                    this.ComandasField = value;
                    this.RaisePropertyChanged("Comandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandas {
            get {
                return this.DetaliiComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliiComandasField, value) != true)) {
                    this.DetaliiComandasField = value;
                    this.RaisePropertyChanged("DetaliiComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto {
            get {
                return this.NumarAutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumarAutoField, value) != true)) {
                    this.NumarAutoField = value;
                    this.RaisePropertyChanged("NumarAuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Sasiu Sasiu {
            get {
                return this.SasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SasiuField, value) != true)) {
                    this.SasiuField = value;
                    this.RaisePropertyChanged("Sasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId {
            get {
                return this.SasiuIdField;
            }
            set {
                if ((this.SasiuIdField.Equals(value) != true)) {
                    this.SasiuIdField = value;
                    this.RaisePropertyChanged("SasiuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu {
            get {
                return this.SerieSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieSasiuField, value) != true)) {
                    this.SerieSasiuField = value;
                    this.RaisePropertyChanged("SerieSasiu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliiComanda", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DetaliiComanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Automobil AutomobilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Comanda ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetaliiComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Imagine ImagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImagineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Mecanic MecanicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MecanicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Operatie OperatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatieIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Automobil Automobil {
            get {
                return this.AutomobilField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomobilField, value) != true)) {
                    this.AutomobilField = value;
                    this.RaisePropertyChanged("Automobil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Comanda Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId {
            get {
                return this.ComandaIdField;
            }
            set {
                if ((this.ComandaIdField.Equals(value) != true)) {
                    this.ComandaIdField = value;
                    this.RaisePropertyChanged("ComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliiComandaId {
            get {
                return this.DetaliiComandaIdField;
            }
            set {
                if ((this.DetaliiComandaIdField.Equals(value) != true)) {
                    this.DetaliiComandaIdField = value;
                    this.RaisePropertyChanged("DetaliiComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Imagine Imagine {
            get {
                return this.ImagineField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagineField, value) != true)) {
                    this.ImagineField = value;
                    this.RaisePropertyChanged("Imagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagineId {
            get {
                return this.ImagineIdField;
            }
            set {
                if ((this.ImagineIdField.Equals(value) != true)) {
                    this.ImagineIdField = value;
                    this.RaisePropertyChanged("ImagineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Mecanic Mecanic {
            get {
                return this.MecanicField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicField, value) != true)) {
                    this.MecanicField = value;
                    this.RaisePropertyChanged("Mecanic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId {
            get {
                return this.MecanicIdField;
            }
            set {
                if ((this.MecanicIdField.Equals(value) != true)) {
                    this.MecanicIdField = value;
                    this.RaisePropertyChanged("MecanicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Operatie Operatie {
            get {
                return this.OperatieField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatieField, value) != true)) {
                    this.OperatieField = value;
                    this.RaisePropertyChanged("Operatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId {
            get {
                return this.OperatieIdField;
            }
            set {
                if ((this.OperatieIdField.Equals(value) != true)) {
                    this.OperatieIdField = value;
                    this.RaisePropertyChanged("OperatieId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.Automobil[] AutomobilsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodSasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.Automobil[] Automobils {
            get {
                return this.AutomobilsField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomobilsField, value) != true)) {
                    this.AutomobilsField = value;
                    this.RaisePropertyChanged("Automobils");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu {
            get {
                return this.CodSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSasiuField, value) != true)) {
                    this.CodSasiuField = value;
                    this.RaisePropertyChanged("CodSasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId {
            get {
                return this.SasiuIdField;
            }
            set {
                if ((this.SasiuIdField.Equals(value) != true)) {
                    this.SasiuIdField = value;
                    this.RaisePropertyChanged("SasiuId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataImagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImagineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitluField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataImagine {
            get {
                return this.DataImagineField;
            }
            set {
                if ((this.DataImagineField.Equals(value) != true)) {
                    this.DataImagineField = value;
                    this.RaisePropertyChanged("DataImagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandas {
            get {
                return this.DetaliiComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliiComandasField, value) != true)) {
                    this.DetaliiComandasField = value;
                    this.RaisePropertyChanged("DetaliiComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagineId {
            get {
                return this.ImagineIdField;
            }
            set {
                if ((this.ImagineIdField.Equals(value) != true)) {
                    this.ImagineIdField = value;
                    this.RaisePropertyChanged("ImagineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu {
            get {
                return this.TitluField;
            }
            set {
                if ((object.ReferenceEquals(this.TitluField, value) != true)) {
                    this.TitluField = value;
                    this.RaisePropertyChanged("Titlu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MecanicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandas {
            get {
                return this.DetaliiComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliiComandasField, value) != true)) {
                    this.DetaliiComandasField = value;
                    this.RaisePropertyChanged("DetaliiComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId {
            get {
                return this.MecanicIdField;
            }
            set {
                if ((this.MecanicIdField.Equals(value) != true)) {
                    this.MecanicIdField = value;
                    this.RaisePropertyChanged("MecanicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/Proiect1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TimpExecutieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect3WPF.ServiceReference1.DetaliiComanda[] DetaliiComandas {
            get {
                return this.DetaliiComandasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliiComandasField, value) != true)) {
                    this.DetaliiComandasField = value;
                    this.RaisePropertyChanged("DetaliiComandas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId {
            get {
                return this.OperatieIdField;
            }
            set {
                if ((this.OperatieIdField.Equals(value) != true)) {
                    this.OperatieIdField = value;
                    this.RaisePropertyChanged("OperatieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TimpExecutie {
            get {
                return this.TimpExecutieField;
            }
            set {
                if ((this.TimpExecutieField.Equals(value) != true)) {
                    this.TimpExecutieField = value;
                    this.RaisePropertyChanged("TimpExecutie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClients", ReplyAction="http://tempuri.org/IService1/GetClientsResponse")]
        Proiect3WPF.ServiceReference1.Client[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClients", ReplyAction="http://tempuri.org/IService1/GetClientsResponse")]
        System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Client[]> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddClient", ReplyAction="http://tempuri.org/IService1/AddClientResponse")]
        void AddClient(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddClient", ReplyAction="http://tempuri.org/IService1/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        void UpdateClient(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        void DeleteClient(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(Proiect3WPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAutomobils", ReplyAction="http://tempuri.org/IService1/GetAutomobilsResponse")]
        Proiect3WPF.ServiceReference1.Automobil[] GetAutomobils(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAutomobils", ReplyAction="http://tempuri.org/IService1/GetAutomobilsResponse")]
        System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Automobil[]> GetAutomobilsAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCar", ReplyAction="http://tempuri.org/IService1/AddCarResponse")]
        void AddCar(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCar", ReplyAction="http://tempuri.org/IService1/AddCarResponse")]
        System.Threading.Tasks.Task AddCarAsync(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCar", ReplyAction="http://tempuri.org/IService1/UpdateCarResponse")]
        void UpdateCar(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCar", ReplyAction="http://tempuri.org/IService1/UpdateCarResponse")]
        System.Threading.Tasks.Task UpdateCarAsync(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCar", ReplyAction="http://tempuri.org/IService1/DeleteCarResponse")]
        void DeleteCar(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCar", ReplyAction="http://tempuri.org/IService1/DeleteCarResponse")]
        System.Threading.Tasks.Task DeleteCarAsync(Proiect3WPF.ServiceReference1.Automobil auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientbyName", ReplyAction="http://tempuri.org/IService1/GetClientbyNameResponse")]
        Proiect3WPF.ServiceReference1.Client GetClientbyName(string nume, string prenume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientbyName", ReplyAction="http://tempuri.org/IService1/GetClientbyNameResponse")]
        System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Client> GetClientbyNameAsync(string nume, string prenume);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Proiect3WPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Proiect3WPF.ServiceReference1.IService1>, Proiect3WPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Proiect3WPF.ServiceReference1.Client[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Client[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public void AddClient(Proiect3WPF.ServiceReference1.Client client) {
            base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(Proiect3WPF.ServiceReference1.Client client) {
            return base.Channel.AddClientAsync(client);
        }
        
        public void UpdateClient(Proiect3WPF.ServiceReference1.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(Proiect3WPF.ServiceReference1.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public void DeleteClient(Proiect3WPF.ServiceReference1.Client client) {
            base.Channel.DeleteClient(client);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(Proiect3WPF.ServiceReference1.Client client) {
            return base.Channel.DeleteClientAsync(client);
        }
        
        public Proiect3WPF.ServiceReference1.Automobil[] GetAutomobils(int clientId) {
            return base.Channel.GetAutomobils(clientId);
        }
        
        public System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Automobil[]> GetAutomobilsAsync(int clientId) {
            return base.Channel.GetAutomobilsAsync(clientId);
        }
        
        public void AddCar(Proiect3WPF.ServiceReference1.Automobil auto) {
            base.Channel.AddCar(auto);
        }
        
        public System.Threading.Tasks.Task AddCarAsync(Proiect3WPF.ServiceReference1.Automobil auto) {
            return base.Channel.AddCarAsync(auto);
        }
        
        public void UpdateCar(Proiect3WPF.ServiceReference1.Automobil auto) {
            base.Channel.UpdateCar(auto);
        }
        
        public System.Threading.Tasks.Task UpdateCarAsync(Proiect3WPF.ServiceReference1.Automobil auto) {
            return base.Channel.UpdateCarAsync(auto);
        }
        
        public void DeleteCar(Proiect3WPF.ServiceReference1.Automobil auto) {
            base.Channel.DeleteCar(auto);
        }
        
        public System.Threading.Tasks.Task DeleteCarAsync(Proiect3WPF.ServiceReference1.Automobil auto) {
            return base.Channel.DeleteCarAsync(auto);
        }
        
        public Proiect3WPF.ServiceReference1.Client GetClientbyName(string nume, string prenume) {
            return base.Channel.GetClientbyName(nume, prenume);
        }
        
        public System.Threading.Tasks.Task<Proiect3WPF.ServiceReference1.Client> GetClientbyNameAsync(string nume, string prenume) {
            return base.Channel.GetClientbyNameAsync(nume, prenume);
        }
    }
}
